stages:
  - test

variables:
  GO_VERSION: "1.21"

test:
  stage: test
  image: golang:${GO_VERSION}
  before_script:
    - apt-get update -y
    - apt-get install -y libvips-dev
  script:
    - go mod tidy
    - go test -race -cover -coverprofile coverage.out -timeout 180s  github.com/discuitnet/discuit/...
  only:
    - main
    - merge_requests
  # artifacts:
  #   paths:
  #     - coverage.out
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: coverage.out
  # coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)%/'
