image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y libvips-dev
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)