image: golang:latest

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y libvips-dev
    - go install github.com/jstemmer/go-junit-report@latest
    - go install github.com/boumenot/gocover-cobertura@latest
  script:
    - go test -coverprofile=coverage.out -covermode=count $(go list ./... | grep -v /vendor/) | go-junit-report > report.xml
    - go tool cover -func=coverage.out
    - gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    when: always
    paths:
      - report.xml
      - coverage.out
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)%/'
