when:
  - event: [pull_request]
    path:
      include: [infrastructure/k8s/**]
  - event: [push, tag, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - develop

variables:
  - &azure_aks_helm_cli "automationwatchdog/azure-aks-helm-cli:latest"
  - &when
    path:
      - '.woodpecker/.k8s.yml'
      - 'infrastructure/k8s/**'

steps:
  validate-helm-chart:
    image: *azure_aks_helm_cli
    commands:
      - helm lint --quiet --strict infrastructure/k8s/camphouse
    when: *when