when:
  - event: [pull_request, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &trivy_plugin docker.io/woodpeckerci/plugin-trivy:1.1.0

steps:
  backend:
    depends_on: []
    image: *trivy_plugin
    settings:
      skip-dirs: ui/,docs/
    failure: ignore

  docs:
    depends_on: []
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir: docs/
    failure: ignore

  ui:
    depends_on: []
    image: *trivy_plugin
    settings:
      skip-dirs: node_modules/
      dir: ui/
    failure: ignore